name: Check GraphQL
description: Checks your GraphQL endpoint for problems
inputs:
  endpoint:
    description: 'The GraphQL endpoint to check'
    required: true
  auth:
    description: 'The Authorization header to use'
    required: false
    default: ''
  subgraph:
    description: 'Whether the graph is a subgraph'
    required: false
    default: 'false'
outputs:
  error:
    description: 'The description of any error that occurred'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.endpoint }}
    - ${{ inputs.auth }}
