name: Check GraphQL
description: Checks your GraphQL endpoint for problems
inputs:
  endpoint:
    description: 'The GraphQL endpoint to check'
    required: true
outputs:
  error:
    description: 'The description of any error that occurred'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.endpoint }}
