on: [push]
jobs:
  basic_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check GraphQL
        uses: ./
        with:
          endpoint: https://spacex-production.up.railway.app/
  bad_url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check GraphQL
        id: test
        continue-on-error: true
        uses: ./
        with:
          endpoint: https://doesntexist.dylananthony.com
      - name: Verify failure
        if: steps.test.outputs.error != ''
        run: echo "Failed as expected"
      - name: Unexpected success
        if: steps.test.outputs.error == ''
        run: echo "Succeeded unexpectedly" && exit 1

